route:
    GET:
        /:                                          contacts@index
        /api/contact/list:                          contacts@list
        /api/contact/view/{id}:                     contacts@view
        /api/contact/find/email:                    contacts@findByEmail
    POST:
        /api/contact/add:                           contacts@add
        /api/contact/update/{id}:                   contacts@update
        /api/contact/delete/{id}:                   contacts@delete
