route:
    GET:
        /:                                          contacts@helloWorld
        /add:                                       contacts@add
        /edit:                                      contacts@edit
        /all:                                       contacts@all
        /email:                                     contacts@findByEmail
